apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: webapi
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: webapi
    spec:
      containers:
        - env:
            - name: DB_ADDRESS
              value: db
            - name: RABBIT_ADDRESS
              value: msg_broker
          image: webapi
          name: clean-arch
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
